#!/usr/bin/env ruby

require 'etc'

if Etc.getpwuid.uid != 0
	puts "Please run this script as a root (sudo)"
	exit!
end

puts "Welcome to dog installer. What do you want to do?"
puts "1. Install dog\n2. Remove dog"

choice = gets.to_i

case choice
	when 1
		puts "--DOWNLOADING DOG--"
		system("wget https://raw.githubusercontent.com/Tekronet/donwloads/main/dog/dog")
		system("chmod +x dog")
		puts "--DOWNLOADING DEPENDENCIES"
		system("gem install colored")
		puts "--INSTALLING DOG--"
		system("mv dog /usr/bin")
		puts "Dog installed! To know how to use it type 'dog --help'"

	when 2
		if !(File.exists?("/usr/bin/dog"))
			puts "Dog is not installed, so no need to remove it"
		else
			system("rm /usr/bin/dog")
			puts "Dog removed!"
		end
end		

